var annotated_dup =
[
    [ "assetbatch", null, [
      [ "AssetBatch", "classassetbatch_1_1AssetBatch.html", null ]
    ] ],
    [ "assetheader", null, [
      [ "PaletteDef", "classassetheader_1_1PaletteDef.html", null ]
    ] ],
    [ "bsp_utils", null, [
      [ "bspSupportObj", "classbsp__utils_1_1bspSupportObj.html", null ]
    ] ],
    [ "generate", null, [
      [ "File", "classgenerate_1_1File.html", null ]
    ] ],
    [ "screen", null, [
      [ "RadialMenu", "classscreen_1_1RadialMenu.html", null ],
      [ "RadialMenuItem", "classscreen_1_1RadialMenuItem.html", null ],
      [ "RadioButtonGroup", "classscreen_1_1RadioButtonGroup.html", null ]
    ] ],
    [ "widget", null, [
      [ "WidgetDefault", "classwidget_1_1WidgetDefault.html", null ]
    ] ],
    [ "$", "struct_0b.html", null ],
    [ "__display_layer", "struct____display__layer.html", null ],
    [ "ArcDrawState", "structArcDrawState.html", null ],
    [ "GFX2D_OBJ", "structGFX2D__OBJ.html", null ],
    [ "GFX_DISP_INTF_EBI", "structGFX__DISP__INTF__EBI.html", null ],
    [ "GFX_DISP_INTF_PORTGROUP", "structGFX__DISP__INTF__PORTGROUP.html", null ],
    [ "GFX_DISP_INTF_SMC", "structGFX__DISP__INTF__SMC.html", null ],
    [ "GFX_DISP_INTF_SPI", "structGFX__DISP__INTF__SPI.html", null ],
    [ "GFXC_CANVAS", "structGFXC__CANVAS.html", null ],
    [ "gfxColorModeInfo", "structgfxColorModeInfo.html", null ],
    [ "gfxDisplayDriver", "structgfxDisplayDriver.html", null ],
    [ "gfxGraphicsProcessor", "structgfxGraphicsProcessor.html", null ],
    [ "gfxIOCTLArg_DisplaySize", "structgfxIOCTLArg__DisplaySize.html", null ],
    [ "gfxIOCTLArg_LayerArg", "structgfxIOCTLArg__LayerArg.html", null ],
    [ "gfxIOCTLArg_LayerIRQCallback", "structgfxIOCTLArg__LayerIRQCallback.html", null ],
    [ "gfxIOCTLArg_LayerPosition", "structgfxIOCTLArg__LayerPosition.html", null ],
    [ "gfxIOCTLArg_LayerRect", "structgfxIOCTLArg__LayerRect.html", null ],
    [ "gfxIOCTLArg_LayerSize", "structgfxIOCTLArg__LayerSize.html", null ],
    [ "gfxIOCTLArg_LayerValue", "structgfxIOCTLArg__LayerValue.html", null ],
    [ "gfxIOCTLArg_Palette", "structgfxIOCTLArg__Palette.html", null ],
    [ "gfxIOCTLArg_Value", "structgfxIOCTLArg__Value.html", null ],
    [ "gfxLayerState", "structgfxLayerState.html", null ],
    [ "gfxPixelBuffer", "structgfxPixelBuffer.html", null ],
    [ "gfxPoint", "structgfxPoint.html", null ],
    [ "gfxRect", "structgfxRect.html", null ],
    [ "gfxSize", "structgfxSize.html", null ],
    [ "gpu_blend", "structgpu__blend.html", null ],
    [ "gpu_buffer", "structgpu__buffer.html", "structgpu__buffer" ],
    [ "gpu_instruction_blend", "structgpu__instruction__blend.html", null ],
    [ "gpu_instruction_copy", "structgpu__instruction__copy.html", null ],
    [ "gpu_instruction_fill", "structgpu__instruction__fill.html", null ],
    [ "gpu_instruction_ldr", "structgpu__instruction__ldr.html", null ],
    [ "gpu_instruction_rop", "structgpu__instruction__rop.html", null ],
    [ "gpu_instruction_str", "structgpu__instruction__str.html", null ],
    [ "gpu_instruction_wfe", "structgpu__instruction__wfe.html", null ],
    [ "gpu_rectangle", "structgpu__rectangle.html", "structgpu__rectangle" ],
    [ "gpu_rop", "structgpu__rop.html", null ],
    [ "ILI9488_DRV", "structILI9488__DRV.html", null ],
    [ "LAYER_ATTRIBUTES", "structLAYER__ATTRIBUTES.html", null ],
    [ "LCDC_DMA_DESC", "structLCDC__DMA__DESC.html", null ],
    [ "leArcQuadrantQuery", "structleArcQuadrantQuery.html", null ],
    [ "leArcWidget", "structleArcWidget.html", "structleArcWidget" ],
    [ "leArray", "structleArray.html", "structleArray" ],
    [ "leBlendLookupTable", "structleBlendLookupTable.html", "structleBlendLookupTable" ],
    [ "leColorModeInfo", "structleColorModeInfo.html", "structleColorModeInfo" ],
    [ "leCStringRenderRequest", "structleCStringRenderRequest.html", null ],
    [ "leDisplayDriver", "structleDisplayDriver.html", null ],
    [ "leDynamicString", "structleDynamicString.html", "structleDynamicString" ],
    [ "leEditWidget", "structleEditWidget.html", null ],
    [ "leEditWidgetVTable", "structleEditWidgetVTable.html", null ],
    [ "leEvent", "structleEvent.html", "structleEvent" ],
    [ "leEventState", "structleEventState.html", "structleEventState" ],
    [ "leFixedString", "structleFixedString.html", "structleFixedString" ],
    [ "leFont", "structleFont.html", null ],
    [ "leFontGlyph", "structleFontGlyph.html", null ],
    [ "leGradient", "structleGradient.html", null ],
    [ "leImage", "structleImage.html", null ],
    [ "leImageDecoder", "structleImageDecoder.html", null ],
    [ "leImageMap", "structleImageMap.html", null ],
    [ "leInputState", "structleInputState.html", null ],
    [ "leLayerState", "structleLayerState.html", null ],
    [ "leList", "structleList.html", "structleList" ],
    [ "leListNode", "structleListNode.html", "structleListNode" ],
    [ "leMargin", "structleMargin.html", "structleMargin" ],
    [ "leMonoDecodeStage", "structleMonoDecodeStage.html", null ],
    [ "lePalette", "structlePalette.html", "structlePalette" ],
    [ "lePixelBuffer", "structlePixelBuffer.html", null ],
    [ "lePoint", "structlePoint.html", null ],
    [ "leRasterFont", "structleRasterFont.html", null ],
    [ "leRect", "structleRect.html", null ],
    [ "leRectArray", "structleRectArray.html", "structleRectArray" ],
    [ "leRenderLayerState", "structleRenderLayerState.html", null ],
    [ "leRenderState", "structleRenderState.html", null ],
    [ "leResolvedAngleRanges", "structleResolvedAngleRanges.html", null ],
    [ "leScheme", "structleScheme.html", null ],
    [ "leSchemeColorTable", "unionleSchemeColorTable.html", null ],
    [ "leSize", "structleSize.html", "structleSize" ],
    [ "leState", "structleState.html", "structleState" ],
    [ "leStreamDescriptor", "structleStreamDescriptor.html", "structleStreamDescriptor" ],
    [ "leString", "structleString.html", "structleString" ],
    [ "leStringInfo", "structleStringInfo.html", null ],
    [ "leStringRenderRequest", "structleStringRenderRequest.html", null ],
    [ "leStringTable", "structleStringTable.html", null ],
    [ "leStringTableEntry", "structleStringTableEntry.html", null ],
    [ "leStringTableHeader", "structleStringTableHeader.html", null ],
    [ "leStringTableIndex", "structleStringTableIndex.html", null ],
    [ "leStringVTable", "structleStringVTable.html", null ],
    [ "leTableString", "structleTableString.html", null ],
    [ "leTouchState", "structleTouchState.html", "structleTouchState" ],
    [ "leUStringRenderRequest", "structleUStringRenderRequest.html", null ],
    [ "leWidget", "structleWidget.html", null ],
    [ "leWidget_MoveEvent", "structleWidget__MoveEvent.html", null ],
    [ "leWidget_ResizeEvent", "structleWidget__ResizeEvent.html", null ],
    [ "leWidgetEvent", "structleWidgetEvent.html", null ],
    [ "leWidgetEvent_TouchDown", "structleWidgetEvent__TouchDown.html", null ],
    [ "leWidgetEvent_TouchMove", "structleWidgetEvent__TouchMove.html", null ],
    [ "leWidgetEvent_TouchUp", "structleWidgetEvent__TouchUp.html", null ],
    [ "leWidgetEventFilter", "structleWidgetEventFilter.html", "structleWidgetEventFilter" ],
    [ "n2d_buffer", "structn2d__buffer.html", "structn2d__buffer" ],
    [ "n2d_module_parameters", "structn2d__module__parameters.html", "structn2d__module__parameters" ],
    [ "n2d_point", "structn2d__point.html", "structn2d__point" ],
    [ "n2d_rectangle", "structn2d__rectangle.html", "structn2d__rectangle" ]
];